import React, { useState } from "react";
import { ReactComponent as SliderIcon } from "../assets/slider-icon.svg";
import "./ComparisionSlider.css";

const ComparisonSlider = ({ beforeImage, afterImage }) => {
  const [sliderPosition, setSliderPosition] = useState(95);
  const [transitionStyles, setTransitionStyles] = useState({
    sliderLine: "",
    beforeImage: "",
  });

  const handleOnChange = (e) => {
    setSliderPosition(e.target.value);
    setTransitionStyles({ sliderLine: "", beforeImage: "" });
  };

  const handleRelease = () => {
    const newSliderPosition = sliderPosition > 50 ? 95 : 5;
    setTransitionStyles({
      sliderLine: "left 1s ease",
      beforeImage: "width 1s ease",
    });
    setSliderPosition(newSliderPosition);
  };

  return (
    <div className="container">
      <div className="container-image">
        <h3
          className="before-label"
          style={{ opacity: sliderPosition < 50 ? 0 : 1 }}
        >
          Before
        </h3>
        <h3
          className="after-label"
          style={{ opacity: sliderPosition > 50 ? 0 : 1 }}
        >
          After
        </h3>
        <p style={{ opacity: sliderPosition > 50 ? 1 : 0 }}>
          Generated by ClinicOS
        </p>
        <img className="after-image" src={afterImage} />
        <img
          className="before-image"
          src={beforeImage}
          style={{
            width: `${sliderPosition}%`,
            transition: transitionStyles.beforeImage,
          }}
        />
        <div
          className="slider-line"
          style={{
            left: `${sliderPosition}%`,
            transition: transitionStyles.sliderLine,
          }}
        >
          <SliderIcon className="slider-icon" />
        </div>
        <input
          className="slider"
          type="range"
          min="0"
          max="100"
          value={sliderPosition}
          onChange={handleOnChange}
          onMouseUp={handleRelease}
          onTouchEnd={handleRelease}
        />
      </div>
    </div>
  );
};

export default ComparisonSlider;
